# Generated by Django 3.2.19 on 2023-05-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['-id'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'ordering': ['-id'], 'verbose_name': 'Configuracion', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='detallepermiso',
            options={'ordering': ['-id'], 'verbose_name': 'Delle Permiso', 'verbose_name_plural': 'Delle Permisos'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['-id'], 'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['-id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['-id'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-id'], 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
