# Generated by Django 3.2.19 on 2023-05-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20230527_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
