# Generated by Django 3.2.19 on 2023-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_autor_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='eliminado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
