# Generated by Django 3.2.19 on 2023-05-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_autor_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='eliminado',
        ),
    ]
